# This is a basic workflow to help you get started with Actions

name: Test Cafe pipeline

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Testing the Project

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        name: Checkout
        
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      
      - uses: actions/setup-node@v2
        name: Setup nodejs 14
        with:
          node-version: '14'
          
      - name: Install node packages
        run: |
          npm install
          npm install -g testcafe
          npm install -g allure-commandline

      # Runs a set of commands using the runners shell
      - name: Run Test Cases
        run: |
          npm test
          
      - name: Generate the Test Report
        if: success() || failure()
        run: |
          allure generate allure/allure-results --clean -o allure/allure-report
          
      - name: Upload Screenshots
        uses: actions/upload-artifact@v2
        with:
          name: Screenshots
          path: "screenshots"
          
      - name: Upload Allure Report
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: "allure/allure-report"
          
